### ISSUE TITLE
Can't load or create worlds with MFR installed, mod conflict

### ISSUE THREAD

**Issue by GammaPaladin** [skyboy/MineFactoryReloaded#517] opened 2015-12-11 17:03 UTC
I have a modpack with a zillion mods in it (Well, 156), which runs fine until I add MFR, at which point it fails back to the main menu whenever I try to create or load a world.

It appears to be a problem with MFR's thaumcraft compatibility code, likely caused by one of the several thaumcraft addons I'm using.

Minecraft also hangs when I try to close it when this problem occurs. The window closes but the process doesn't end, and the launcher doesn't come back up.

I've attached the log, 

[fml-client-latest.log.txt](https://github.com/skyboy/MineFactoryReloaded/files/59641/fml-client-latest.log.txt)

**Comment by skyboy** [comment] 2015-12-11 18:22
This is a bug in thaumcraft triggered by one of the mods adding crucible recipes. Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/446

**Closed by skyboy** 2015-12-11 18:22 UTC
