### ISSUE TITLE
Wat.  I placed down the slaughterhouse and it kicked me off of a multiplayer server... when I was playing single player

### ISSUE THREAD

**Issue by zackeezy** [skyboy/MineFactoryReloaded#627] opened 2017-06-26 22:30 UTC
https://pastebin.com/6p9Akpjx

It did this before, then I updated my game thinking it'd fix it, but it did the same thing after I updated just now.  I was off the grid when it happened the first time but I'm finally back so I just replicated the issue.  

Here's even a video of what happens: https://youtu.be/m8ShMWkHBY0

This time, however, it let me log back into the world without kicking me off again. 

Edit: This is for 1.10.2

**Comment by skyboy** [comment] 2017-06-27 10:13
Duplicate of #616

**Closed by skyboy** 2017-06-27 10:13 UTC
