### ISSUE TITLE
Crash on placing a MFR grinder

### ISSUE THREAD

**Issue by mrdeadlocked** [skyboy/MineFactoryReloaded#406] opened 2015-03-25 01:11 UTC
http://pastebin.com/0qWXSF8h  This happens on placing a mfr grinder on dirt nothing attached. I then can't load up world without editting out the grinder.

**Comment by skyboy** [comment] 2015-03-26 14:33
Duplicate of #393

**Closed by skyboy** 2015-03-26 14:33 UTC

**Comment by trekkie22** [comment] 2016-05-17 15:25
I had the same issue as well and was able to narrow it down to the mod "Streams". If Streams is installed in my modpack, the MFR Grinder crashes on placing, right-click or, if waila is active, even on looking at the Grinder. To solve the problem, remove Streams and, that's important, the corresponding CoreMod "Farseek". Be aware that Streams changes the World generation, so you may experience odd world generation. Also the rivers look odd because Streams uses a modified water source block and removing streams results in empty rivers.

If you want to keep streams, you can temporarily remove waila. Without waila you can join the world and remove the Grinder in creative. With waila (or any other similar mod that displays information about blocks) active, minecraft crashes immediately on logging in because your char looks at the block so that it is activated by waila to read the block information. After removing the Grinder, you can re-activate waila, but the Grinder and several other machines (like the Slaugtherhouse) remain unusable.
