### ISSUE TITLE
Alpha builds are useless

### ISSUE THREAD

**Issue by scj643** [skyboy/MineFactoryReloaded#496] opened 2015-10-19 20:04 UTC
No one can run the alpha builds that are constantly pushed to curseforge since they are using unreleased versions of CoFH core. This is not acceptable in my opinion.

**Comment by skyboy** [comment] 2015-10-19 23:35
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/485

**Closed by skyboy** 2015-10-19 23:35 UTC

**Comment by Protheus** [comment] 2015-10-20 07:49
When I asked politely for the COFH Core you marked as duplicated and closed it and never answered our questions.

Yes it is your work but without the community to play YOUR work you are what... ?

Instead of just dismissing this as a duplicate you could have taken the time to inform us in a more polite manner on why you have used a COFH Core that is nowhere to be found or only to paying (they sign your checks I guess) players !

**Comment by scj643** [comment] 2015-10-20 11:40
I agree there is no point to open source if it isn't usable.

**Comment by skyboy** [comment] 2015-10-20 19:43
Open source and readily available pre-built unstable versions of software are not equatable concepts. When the next release is ready, things will be available.
