### ISSUE TITLE
Builds 137+ do not work.

### ISSUE THREAD

**Issue by Zilacon** [skyboy/MineFactoryReloaded#523] opened 2015-12-23 16:18 UTC
Ive been waiting for a working release of MFR for a long time. Well over a month.
Every version past 136 will crash at the end of the client start up.

And the crash report makes zero sense to me.
A working version of 168 would be nice.
[crash-2015-12-23_08.18.09-client.txt](https://github.com/skyboy/MineFactoryReloaded/files/70990/crash-2015-12-23_08.18.09-client.txt)

**Comment by skyboy** [comment] 2015-12-23 18:50
First: MFR hasn't had a release in a lot longer than a month. Everything you've been using is an alpha and may corrupt your world. Don't use them unless you're fine with everything you've done potentially being erased.

Second: Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/518

**Closed by skyboy** 2015-12-23 18:50 UTC
