### ISSUE TITLE
Broken ore dictionary registration 

### ISSUE THREAD

**Issue by Xen1290** [skyboy/MineFactoryReloaded#509] opened 2015-11-15 16:45 UTC
[17:20:19] [Client thread/WARN] [FML]: ****************************************
[17:20:19] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name listAllmilk has occurred. It adds an item (type: class powercrystals.minefactoryreloaded.MineFactoryReloadedCore$1) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod MineFactory Reloaded report it to them!
[17:20:19] [Client thread/WARN] [FML]: * at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[17:20:19] [Client thread/WARN] [FML]: * at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[17:20:19] [Client thread/WARN] [FML]: * at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:499)
[17:20:19] [Client thread/WARN] [FML]: * at powercrystals.minefactoryreloaded.setup.recipe.Vanilla.registerOredict(Vanilla.java:125)
[17:20:19] [Client thread/WARN] [FML]: * at powercrystals.minefactoryreloaded.MineFactoryReloadedCore.preInit(MineFactoryReloadedCore.java:529)
[17:20:19] [Client thread/WARN] [FML]: * at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[17:20:19] [Client thread/WARN] [FML]: ****************************************

@skyboy 
Latest Rrecommended Forge: 1558
MineFactoryReloaded 2.8.0

**Comment by skyboy** [comment] 2015-11-16 03:38
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/503

**Closed by skyboy** 2015-11-16 03:38 UTC
