### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by Wasabules** [skyboy/MineFactoryReloaded#512] opened 2015-11-28 16:59 UTC
28.11 17:51:51 [Server] INFO [17:51:51] [Server thread/WARN] [FML]: ****************************************
28.11 17:51:51 [Server] INFO [17:51:51] [Server thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
28.11 17:51:51 [Server] INFO [17:51:51] [Server thread/WARN] [FML]: *  at powercrystals.minefactoryreloaded.MineFactoryReloadedCore.preInit(MineFactoryReloadedCore.java:529)
28.11 17:51:51 [Server] INFO [17:51:51] [Server thread/WARN] [FML]: *  at powercrystals.minefactoryreloaded.setup.recipe.Vanilla.registerOredict(Vanilla.java:125)
28.11 17:51:51 [Server] INFO [17:51:51] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:499)
28.11 17:51:51 [Server] INFO [17:51:51] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
28.11 17:51:51 [Server] INFO [17:51:51] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
28.11 17:51:51 [Server] INFO TO USERS: YES this is a BUG in the mod MineFactory Reloaded report it to them!
28.11 17:51:51 [Server] INFO [17:51:51] [Server thread/WARN] [FML]: * A broken ore dictionary registration with name listAllmilk has occurred. It adds an item (type: class powercrystals.minefactoryreloaded.MineFactoryReloadedCore$1) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
28.11 17:51:51 [Server] INFO [17:51:51] [Server thread/WARN] [FML]: ****************************************

**Comment by skyboy** [comment] 2015-11-29 00:11
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/503

**Closed by skyboy** 2015-11-29 00:11 UTC
