### ISSUE TITLE
SMASHER/GRINDER/SLAUGHTERHOUSE New bug ><'

### ISSUE THREAD

**Issue by 1ChaVnere** [skyboy/MineFactoryReloaded#628] opened 2017-06-27 13:01 UTC
Hi I'm back again because I've experienced maybe 3 new bugs while I was playing with CofhCore 4.1.8.12, and MFR 2.9.0B1-233. In fact I'm still playing in a modpack with a bunh of other mods (tell me if you want a  precise list), when I place a grinder or a slaughterhouse it just disconnect me from the map as if I'm playing on a server (so no crash) and I don't understand the issue seemed fixed but I'm experiencing it with the latest builds from curseforge. So here are the errors with both block : 

[GRINDER.txt](https://github.com/skyboy/MineFactoryReloaded/files/1105318/GRINDER.txt)
[SLAUGHTERHOUSE.txt](https://github.com/skyboy/MineFactoryReloaded/files/1105320/SLAUGHTERHOUSE.txt)

And the second bug happens when I'm placing a smasher, my game just crash and I don't know why, so here is the smasher error with crashlogs
[SMASHER.txt](https://github.com/skyboy/MineFactoryReloaded/files/1105326/SMASHER.txt)

**Comment by P3pp3rF1y** [comment] 2017-06-27 14:05
yeah, so all of these are one thing - bad mapping to obfuscated name for rand field - my bad. I will get a fix  done, but it will require another build of cofhcore so it may take a few days to release

**Comment by P3pp3rF1y** [comment] 2017-06-27 15:04
Actually looks like skyboy has already fixed this in dev so once that change is released with next release of CoFHCore this issue will go away.

**Comment by 1ChaVnere** [comment] 2017-06-27 16:57
ok perfect :)

**Comment by skyboy** [comment] 2017-06-28 00:00
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/616#issuecomment-311203224

**Closed by skyboy** 2017-06-28 00:00 UTC
Labels: duplicate
