### ISSUE TITLE
World completly froze when I place a slaughterhouse in modpack

### ISSUE THREAD

**Issue by 1ChaVnere** [skyboy/MineFactoryReloaded#623] opened 2017-06-25 17:57 UTC
Hi, it's me again maybe I've found a bug but i think you already knows it cuz the item in question is uncraftable, so I was testing all the uncraftable blocks on a flat world with all my mods and when I placed the slaughterhouse the map completly froze, again I had to delte and reinstall the mod to delete the block from the world. I checked the logs and here isthe problematic stuff : 

[SLAUGHTERHOUSE BUG.txt](https://github.com/skyboy/MineFactoryReloaded/files/1100508/SLAUGHTERHOUSE.BUG.txt)

Are all the uncraftable blocks and things buggy ?

**Comment by P3pp3rF1y** [comment] 2017-06-26 12:38
I can't see which version of cofhcore you're using, but please try again with the latest one released that should fix this issue. 

And I assume that you have enderio recipes turned on, those are not done yet and thus some items don't have recipes. However if you turn these off to just use default MFR ones you should see recipes for all blocks/items.

**Comment by skyboy** [comment] 2017-06-27 10:13
Duplicate of #616

**Closed by skyboy** 2017-06-27 10:13 UTC
Labels: duplicate
