### ISSUE TITLE
This mod is causing Industrial Craft 2 displaying incorrectly.

### ISSUE THREAD

**Issue by jimchen5209** [skyboy/MineFactoryReloaded#635] opened 2017-07-02 11:16 UTC
**_Minecraft Version: 1.10.2_**

## Without MineFactoryReloaded:

**Installed Mods:**

>  Industrial Craft 2
>  Jei

**ScreenShot:**
![image](https://user-images.githubusercontent.com/10269287/27769291-8ba25698-5f59-11e7-9acb-9c271c151e65.png)

## With MineFactoryReloaded:

**Installed Mods:**

>  Industrial Craft 2
>  Jei
>  MinefactoryReloaded
>  CodeChickenLib (Coremod of MFR)
>  CoFHCore (Coremod of MFR)

**Screenshot:**
![image](https://user-images.githubusercontent.com/10269287/27769341-18753b6c-5f5a-11e7-8ec1-2d8856274069.png)

## Without MineFactoryReloaded but with core mods:

**Installed Mods:**

>  Industrial Craft 2
>  Jei
>  CodeChickenLib (Coremod of MFR)
>  CoFHCore (Coremod of MFR)

**Screenshot:**
![image](https://user-images.githubusercontent.com/10269287/27769361-81079468-5f5a-11e7-9822-114c78fa1ef8.png)

**Comment by skyboy** [comment] 2017-07-02 12:17
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/633

**Closed by skyboy** 2017-07-02 12:17 UTC
