### ISSUE TITLE
[Enhancement] Better Method of Drinking Essence "Diamond Straw" ?

### ISSUE THREAD

**Issue by mikeloeven** [skyboy/MineFactoryReloaded#493] opened 2015-10-15 07:33 UTC
Getting personal levels from essence is a real pain I think MFR needs an upgraded diamond straw

For flavor text something like

"This straw is reinforced with diamonds allowing it to punch through tank walls so the player can drink essence directly from any fluid storage device at faster rate

If you think this idea is stupid you could always do something like openblocks's XP shower

**Comment by skyboy** [comment] 2015-10-15 12:55
Technically at present you can use syringes, TE's fluid transposer and autonomous activator to do the same thing; which is why I haven't put any substantial dev time into implementing the feature. No diamond straw though, just plastic.

Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/462

**Closed by skyboy** 2015-10-15 12:55 UTC
