### ISSUE TITLE
Crash after updating MFR

### ISSUE THREAD

**Issue by Keyarose** [skyboy/MineFactoryReloaded#543] opened 2016-03-20 01:00 UTC
Hello, I'm getting a crash during startup after updating MFR.
Crash Log: http://pastebin.com/7zpryck5

Version Updated to: 2.8.1-174
Version Updated from: 2.8.0-104

**Comment by skyboy** [comment] 2016-03-20 01:36
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/518

**Closed by skyboy** 2016-03-20 01:36 UTC

**Comment by Keyarose** [comment] 2016-03-20 17:49
Updating Technomancy fixed it for me, thanks for pointing me that way.
