### ISSUE TITLE
Help !! Mfr stops game from loading 

### ISSUE THREAD

**Issue by Gamingdaredevil** [skyboy/MineFactoryReloaded#504] opened 2015-10-30 00:18 UTC
![mfr error](https://cloud.githubusercontent.com/assets/10699370/10835501/05246b9c-7e9b-11e5-9801-97779fab666c.png)

i'm using CoFHCore-[1.7.10]3.0.4B1-308

**Comment by skyboy** [comment] 2015-10-30 03:18
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/485

**Closed by skyboy** 2015-10-30 03:18 UTC
