### ISSUE TITLE
Block Smasher Crash

### ISSUE THREAD

**Issue by 1ChaVnere** [skyboy/MineFactoryReloaded#636] opened 2017-07-02 19:36 UTC
I'm playing on modpack and each time i place a block smasher the game crash and i've to load the map without mfr to erase the block.
[crash-2017-07-02_21.33.09-client.txt](https://github.com/skyboy/MineFactoryReloaded/files/1118032/crash-2017-07-02_21.33.09-client.txt)

**Comment by skyboy** [comment] 2017-07-03 15:44
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/616#issuecomment-311203224

**Closed by skyboy** 2017-07-03 15:44 UTC

**Comment by 1ChaVnere** [comment] 2017-07-03 16:20
BUT THE BUG ISN'T FIXEX WITH THE LAST VERSIONS OF COFHCORE AND MFR

**Comment by 1ChaVnere** [comment] 2017-07-03 16:20
woops sorry for maj
