### ISSUE TITLE
No release required CoFHCore.

### ISSUE THREAD

**Issue by Tsyklop** [skyboy/MineFactoryReloaded#500] opened 2015-10-23 05:29 UTC
No release required CoFHCore. Where to find this version?
MFR, ranging from the 132 version requires COFHCore - which is not ...

**Comment by Tsyklop** [comment] 2015-10-23 05:30
https://github.com/skyboy/MineFactoryReloaded/issues/491

**Comment by skyboy** [comment] 2015-10-23 17:17
Duplicate of #485

**Closed by skyboy** 2015-10-23 17:17 UTC
