### ISSUE TITLE
Crash when trying to use the auto spawner to spawn blazes. 

### ISSUE THREAD

**Issue by zackeezy** [skyboy/MineFactoryReloaded#607] opened 2017-06-20 04:19 UTC
MC: 1.10.2
Forge: 12.18.3.2254
MFR: 2.9.0B1
Crash Log: https://pastebin.com/203FCYJ3

**Comment by skyboy** [comment] 2017-06-20 04:38
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/605

**Closed by skyboy** 2017-06-20 04:38 UTC
