### ISSUE TITLE
Lakes of sewage and sludge in superflat despite config set to no.

### ISSUE THREAD

**Issue by donqixot** [skyboy/MineFactoryReloaded#521] opened 2015-12-20 14:10 UTC
If I create superflat world, but exclude lakes from generatorOptions, then water lakes are not created. Yet sewage and sludge lakes are still created. Can this be disabled as well if config says so? It's a big mess to clean it up in survival.

**Comment by skyboy** [comment] 2015-12-21 01:35
Duplicate of #244

**Closed by skyboy** 2015-12-21 01:35 UTC
