### ISSUE TITLE
Crash with MFR 2.8.1-174

### ISSUE THREAD

**Issue by dhalek** [skyboy/MineFactoryReloaded#532] opened 2016-01-28 15:03 UTC
After upgrading MFR along with the other Cofh mods I get a crash.

[fml-client-2.txt](https://github.com/skyboy/MineFactoryReloaded/files/108339/fml-client-2.txt)

Reverting to MFL 2.8.0-104 removed this issue.

**Comment by skyboy** [comment] 2016-01-28 23:38
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/518

**Closed by skyboy** 2016-01-28 23:38 UTC
