### ISSUE TITLE
Newest Build Issues

### ISSUE THREAD

**Issue by ZeekDaGeek** [skyboy/MineFactoryReloaded#486] opened 2015-09-26 01:32 UTC
The newest build of MFR required CoFH core version 3.1.0b1-308. This version doesn't exist, additionally build 308 of CoFH core appears to be 3.0.4b1-308...

Also... HI SKYBOY! geekH

**Comment by skyboy** [comment] 2015-09-26 05:46
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/485

**Closed by skyboy** 2015-09-26 05:46 UTC
