### ISSUE TITLE
CRASH on Placement: MFR Grinder (issue unresolved)

### ISSUE THREAD

**Issue by AnthonyKane5528X** [skyboy/MineFactoryReloaded#616] opened 2017-06-23 20:01 UTC
CRASH on Placement: MFR Grinder & Slaughterhouse(issue unresolved)
CofHcore: 1.10.2-4.1.7.11
Minefactory Reloaded:  [1.10.2]2.9.0B1-220

Previous tickets regarding this issue were closed stating issue was fixed with CofHcore 4.1.7.11
https://github.com/skyboy/MineFactoryReloaded/issues/608

Issues are still unresolved.  Game still crashes upon placing block.  Please re-open and continue investigating problem.

**Comment by kkjdroid** [comment] 2017-06-24 23:40
I can confirm this. New CoFHCore, new world, new grinder, still crashes on placement. [Crash report](https://pastebin.com/63TAR1K2)

**Comment by skyboy** [comment] 2017-06-25 00:53
This time it *should* actually be fixed in the next CoFHCore release. Apparently not all of our ASM was actually running: resolved by https://github.com/CoFH/CoFHCore/commit/a3ea6d8d47223f6f022e02782a430e9978eea00b

**Comment by DeadSix27** [comment] 2017-06-25 12:24
@skyboy Is that the only commit and therefor change required for it to be fixed?
Because with that compiled, the grinder still produces an error:

https://gist.github.com/DeadSix27/f932b7307bddb4ee9dba85d43ba0a438

**Comment by JillSwift** [comment] 2017-06-25 15:32
Ditto: https://paste.ee/p/nEdeP

MineFactoryReloaded-[1.10.2]2.9.0B1-222.jar
CoFHCore-1.10.2-4.1.7.11-universal.jar

**Comment by DeadSix27** [comment] 2017-06-25 15:54
@JillSwift It's not fixed in that version, you have the "old error".

**Comment by JillSwift** [comment] 2017-06-25 19:18
Oop, misread Skyboy's note as most recent not upcoming release.

**Comment by JillSwift** [comment] 2017-06-26 11:50
https://paste.ee/p/TzHAe

MineFactoryReloaded-[1.10.2]2.9.0B1-222.jar
CoFHCore-1.10.2-4.1.8.12-universal.jar

**Comment by kkjdroid** [comment] 2017-06-26 22:47
Still broken on CoFHCore 4.1.8.12: [Log](https://pastebin.com/r89yKG4s)

**Comment by skyboy** [comment] 2017-06-27 10:23
Class loads at least, https://github.com/CoFH/CoFHCore/commit/3653c838d4dd2964f038aceb6703b658d50b9981 will resolve that error when released, and hopefully there are no more.

**Comment by DeadSix27** [comment] 2017-06-27 11:12
@skyboy Just tested this with the fixed cofhcore (self compiled), 'least the grinder works just fine! Altho the slaughterhouse still doesn't produce pink slime, which I guess is due the issue this person PRd, (the typo):

https://github.com/skyboy/MineFactoryReloaded/pull/615/commits/dd66cfa8380e7bfa781d126884ad00bbe9f8d4e5

**Comment by 1ChaVnere** [comment] 2017-06-28 11:51
@DeadSix27 hi dude can you tell me which version of CofhCore you use ? Because I still having all those bugs :/ in #628 even with the 224 build of MFR

**Comment by DeadSix27** [comment] 2017-06-28 12:02
@1ChaVnere https://minecraft.curseforge.com/projects/cofhcore/files/2441735 and https://minecraft.curseforge.com/projects/minefactory-reloaded/files/2442540

**Comment by 1ChaVnere** [comment] 2017-06-28 12:03
@DeadSix27 But I still have the issue from #628 I don't understand

**Comment by DeadSix27** [comment] 2017-06-28 12:15
@1ChaVnere Ah I think cofhcore didn't release their newest version yet, wait for that.

**Comment by 1ChaVnere** [comment] 2017-06-28 12:16
ah ok but why don't you have the bug tho ?

**Comment by DeadSix27** [comment] 2017-06-28 12:37
@1ChaVnere Because I compiled it on my own from the source code, but they probably don't support that. So I wouldn't recommend that.

**Comment by 1ChaVnere** [comment] 2017-06-28 12:39
ok fine thank you for the information ^^

**Comment by accessdenied0** [comment] 2017-06-28 14:11
I had this issue with the Slaughterhouse, too. Funny enough it didn't crashed. One Probe just wasn't able to receive information about the block and I couldn't open it. Finally, after I placed an EnderIO Creative Bank next to it, it crashed. (I experienced this in a creative-test world)

**Comment by DirkSch** [comment] 2017-06-29 07:47
I post a crashreport from the latest MFR on Courseforge.
https://pastebin.com/hBH1AYDL
I place only a Grinder in the world and it crash the server.

**Comment by kkjdroid** [comment] 2017-06-30 00:15
Finally fixed with CoFHCore 4.1.9.13.

**Closed** 2017-06-30 15:12 UTC
Labels: bug
