### ISSUE TITLE
MineFactoryReloaded-[1.10.2]2.9.0B1-226 causing startup crash.

### ISSUE THREAD

**Issue by border999** [skyboy/MineFactoryReloaded#648] opened 2017-07-10 05:38 UTC
It should be noted that optifine is involved most likely: OptiFine_1.10.2_HD_U_E3
https://pastebin.com/Ap9E2KaF
It's some form of rendering error with the milk bucket.

**Comment by skyboy** [comment] 2017-07-11 16:12
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/646

**Closed by skyboy** 2017-07-11 16:12 UTC

**Comment by FlaggedBrad** [comment] 2017-08-04 00:13
Disable milk bottles in your minefactory reloaded config file, it worked for me
