### ISSUE TITLE
[1.10.2] Grinder crashes server

### ISSUE THREAD

**Issue by DeadSix27** [skyboy/MineFactoryReloaded#614] opened 2017-06-23 10:38 UTC
After placing the grinder the server reports a lot of errors and eventually crashes:

Stacktrace: https://gist.github.com/DeadSix27/01976b3a15bd9837e3ea74f1754653e3 (that error got repeated many times)

**Comment by skyboy** [comment] 2017-06-23 10:50
Duplicate of https://github.com/skyboy/MineFactoryReloaded/issues/608

**Closed by skyboy** 2017-06-23 10:50 UTC
