### ISSUE TITLE
Nether Ore/ Minefactory Reloaded Laser Drill Bug

### ISSUE THREAD

**Issue by CrimsonCrystal** [skyboy/MineFactoryReloaded#448] opened 2015-05-23 18:20 UTC
When using a Laser Drill from Minefactory Reloaded, it will sometimes create ores from the mod Nether Ores. However, it produces all the different types of Nether Ores, despite them not spawning naturally. An example is that it would create Nikolite Ore and Green Sapphire Ore despite them not spawning naturally, and having no use in the game itself except for taking up room. 
My solutions for this would be:
A) Make it so that the Laser Drill can only create ores that spawn naturally
B) Add a config to blacklist/whitelist certain ores that the Laser Drill can create
C) (I'm only saying this because I'm pretty sure the creator of Minefactory Reloaded is the creator of Nether Ores, because the configs are in the same folder "powercrystal") Make a config to disable certain ores.

**Comment by skyboy** [comment] 2015-07-20 03:32
Duplicate of #435

**Closed by skyboy** 2015-07-20 03:32 UTC
